# build environment
FROM node:9.6.1 as builder
RUN mkdir /usr/src/frontend
WORKDIR /usr/src/frontend
ENV PATH /usr/src/frontend/node_modules/.bin:$PATH
COPY ./frontend/package.json /usr/src/frontend/package.json
RUN npm install --silent
RUN npm install react-scripts -g --silent
COPY . /usr/src/frontend
RUN npm run build

# production environment
FROM nginx:latest
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx
COPY --from=builder /usr/src/frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]